nelmio_cors:
        defaults:
            allow_credentials: false
            allow_origin: []
            allow_headers: []
            allow_methods: []
            expose_headers: []
            max_age: 0
            hosts: []
            origin_regex: false
        paths:
            '^/':
              allow_credentials: true
              origin_regex: true
              allow_origin: ['*']
              allow_headers: ['*']
              allow_methods: ['POST','GET','DELETE','PUT','OPTIONS', 'GET_LIST']
              expose_headers: ['*']
              max_age: 3600
